<a href="https://colab.research.google.com/github/nishita-ds/Hyperparameter-tuning-using-Optuna/blob/main/optuna_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.48)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 3.8 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [20]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)csv
url = "https://raw.githubusercontent.com/liquidcarrot/data.pima-indians-diabetes/refs/heads/master/src/index.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,pregnancies,plasma glucose concentration,diastolic blood pressure,triceps skinfold thickness,insulin,body mass index,diabetes pedigree function,age,diabetic
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0

In [21]:
import numpy as np
import pandas as pd

# Drop the first row which contains the original string header values
df = df.iloc[1:].copy()

# Convert all columns to numeric, coercing errors to NaN
# This is crucial because all data was read as strings due to the header row initially
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
# Now df.mean() will work correctly as all columns are numeric
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [22]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [24]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-04-07 16:31:11,250] A new study created in memory with name: no-name-633d8411-c8ec-48ba-bd76-5b853102c1b1
[I 2026-04-07 16:31:11,808] Trial 0 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 110, 'max_depth': 3}. Best is trial 0 with value: 0.7597765363128491.
[I 2026-04-07 16:31:12,732] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 162, 'max_depth': 10}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:13,851] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 198, 'max_depth': 13}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:14,731] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 157, 'max_depth': 14}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:15,068] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 59, 'max_depth': 15}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:15,796] Trial 5 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 129, 'max_depth': 10}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:16,455] Trial 6 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 131, 'max_depth': 4}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:17,284] Trial 7 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 156, 'max_depth': 6}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:17,772] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 17}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:18,247] Trial 9 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 82, 'max_depth': 17}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:19,329] Trial 10 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 197, 'max_depth': 9}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:20,989] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 198, 'max_depth': 12}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:22,503] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 169, 'max_depth': 20}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:23,488] Trial 13 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 179, 'max_depth': 8}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:24,496] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 180, 'max_depth': 12}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:25,325] Trial 15 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 147, 'max_depth': 11}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:26,300] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 178, 'max_depth': 7}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:27,088] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 16}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:27,679] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 108, 'max_depth': 5}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:28,628] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 169, 'max_depth': 10}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:29,656] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 20}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-04-07 16:31:31,173] Trial 21 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 177, 'max_depth': 7}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:32,036] Trial 22 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 157, 'max_depth': 8}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:33,410] Trial 23 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 12}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:34,871] Trial 24 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 171, 'max_depth': 6}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:35,877] Trial 25 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 146, 'max_depth': 10}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:36,515] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 117, 'max_depth': 8}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:37,567] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 188, 'max_depth': 13}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:38,480] Trial 28 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 165, 'max_depth': 9}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:38,995] Trial 29 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 102, 'max_depth': 3}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:40,041] Trial 30 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 189, 'max_depth': 11}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:40,999] Trial 31 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 177, 'max_depth': 7}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:41,930] Trial 32 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 175, 'max_depth': 6}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:42,851] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 163, 'max_depth': 13}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:43,664] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 7}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:44,737] Trial 35 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 192, 'max_depth': 14}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:46,147] Trial 36 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 200, 'max_depth': 9}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:47,442] Trial 37 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 160, 'max_depth': 4}. Best is trial 21 with value: 0.7746741154562384.
[I 2026-04-07 16:31:48,472] Trial 38 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 136, 'max_depth': 7}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:49,128] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 126, 'max_depth': 5}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:49,874] Trial 40 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 137, 'max_depth': 7}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:50,637] Trial 41 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 139, 'max_depth': 7}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:51,397] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 138, 'max_depth': 7}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:52,003] Trial 43 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 117, 'max_depth': 5}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:52,542] Trial 44 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 99, 'max_depth': 6}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:53,195] Trial 45 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 135, 'max_depth': 3}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:53,867] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 121, 'max_depth': 8}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:54,638] Trial 47 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 149, 'max_depth': 4}. Best is trial 38 with value: 0.7783985102420856.
[I 2026-04-07 16:31:54,946] Trial 48 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 54, 'max_depth': 7}. Best is trial 48 with value: 0.7802607076350093.
[I 2026-04-07 16:31:55,453] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 94, 'max_depth': 5}. Best is trial 48 with value: 0.7802607076350093.

In [25]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 54, 'max_depth': 7}

In [26]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# Samplers in Optuna

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

# Random Search

In [11]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-04-07 16:19:48,183] A new study created in memory with name: no-name-50ee8910-971a-48f5-a28d-0b2dfe320412
[I 2026-04-07 16:19:49,439] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 58, 'max_depth': 12}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-04-07 16:19:50,292] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 59, 'max_depth': 6}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-07 16:19:51,523] Trial 2 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 8}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-07 16:19:52,695] Trial 3 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 84, 'max_depth': 20}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-07 16:19:53,595] Trial 4 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 85, 'max_depth': 9}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-07 16:19:54,457] Trial 5 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 85, 'max_depth': 17}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-07 16:19:56,251] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 139, 'max_depth': 17}. Best is trial 6 with value: 0.7746741154562384.
[I 2026-04-07 16:19:58,522] Trial 7 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 164, 'max_depth': 9}. Best is trial 6 with value: 0.7746741154562384.
[I 2026-04-07 16:20:01,599] Trial 8 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 196, 'max_depth': 19}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:03,684] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 14}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:05,019] Trial 10 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 138, 'max_depth': 14}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:06,031] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 15}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:06,838] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 119, 'max_depth': 14}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:07,449] Trial 13 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 124, 'max_depth': 3}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:07,818] Trial 14 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 66, 'max_depth': 10}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:08,243] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 74, 'max_depth': 8}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:09,300] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 187, 'max_depth': 15}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:09,867] Trial 17 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 102, 'max_depth': 14}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:10,625] Trial 18 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 138, 'max_depth': 9}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:11,255] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 125, 'max_depth': 4}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:11,749] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 93, 'max_depth': 7}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:12,845] Trial 21 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 180, 'max_depth': 6}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:14,603] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 13}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:15,407] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 91, 'max_depth': 16}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:15,851] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 79, 'max_depth': 17}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:16,764] Trial 25 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 167, 'max_depth': 9}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:17,164] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 72, 'max_depth': 7}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:17,764] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 20}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:18,624] Trial 28 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 178, 'max_depth': 3}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:19,711] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 196, 'max_depth': 14}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:20,510] Trial 30 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 164, 'max_depth': 3}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:21,500] Trial 31 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 185, 'max_depth': 7}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:22,344] Trial 32 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 158, 'max_depth': 7}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:22,702] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 20}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:23,079] Trial 34 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 66, 'max_depth': 10}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:23,474] Trial 35 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 70, 'max_depth': 20}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:24,146] Trial 36 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 138, 'max_depth': 3}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:24,930] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 141, 'max_depth': 11}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:25,319] Trial 38 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 68, 'max_depth': 18}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:26,737] Trial 39 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 162, 'max_depth': 9}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:27,846] Trial 40 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 123, 'max_depth': 10}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:28,429] Trial 41 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 78, 'max_depth': 8}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:28,992] Trial 42 finished with value: 0.7523277467411544 and parameters: {'n_estimators': 102, 'max_depth': 9}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:29,286] Trial 43 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 52, 'max_depth': 19}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:30,133] Trial 44 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 169, 'max_depth': 4}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:31,056] Trial 45 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 18}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:31,611] Trial 46 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 101, 'max_depth': 17}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:32,218] Trial 47 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 107, 'max_depth': 18}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:34,184] Trial 48 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 193, 'max_depth': 3}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-04-07 16:20:35,363] Trial 49 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 106, 'max_depth': 9}. Best is trial 8 with value: 0.7802607076350093.

In [12]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 196, 'max_depth': 19}

In [13]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# Grid Search

In [14]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [15]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-04-07 16:25:06,946] A new study created in memory with name: no-name-2c912add-3773-49c7-b911-fea03286b395
[I 2026-04-07 16:25:08,194] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-04-07 16:25:09,785] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-04-07 16:25:10,323] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:11,310] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:13,236] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:14,262] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:15,382] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:16,225] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:17,066] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:18,177] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:19,292] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:20,416] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:21,446] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-07 16:25:21,713] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-04-07 16:25:22,287] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-04-07 16:25:22,572] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [16]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [17]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# Optuna Visualization

In [27]:
# For visualization
from optuna.visualization import plot_optimization_history,plot_parallel_coordinate,plot_slice,plot_contour,plot_param_importances

In [28]:
# 1.Optimization History
plot_optimization_history(study).show()

In [29]:
# 2. Parallel coordinate plot
plot_parallel_coordinate(study).show()

In [30]:
# 3.Slice plot
plot_slice(study).show()

In [31]:
# 4.Contour plot
plot_contour(study).show()

In [32]:
# Hyperparameter Importances
plot_param_importances(study).show()

# Optimizing Multiple ML Models

In [33]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [34]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [35]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-04-07 16:47:04,951] A new study created in memory with name: no-name-7afcb41e-3fc3-480d-887e-8973f5930dd2
[I 2026-04-07 16:47:07,780] Trial 0 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 214, 'max_depth': 18, 'min_samples_split': 10, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-07 16:47:07,926] Trial 1 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 0.881277946095126, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-07 16:47:07,972] Trial 2 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.38091221405647246, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-04-07 16:47:09,153] Trial 3 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 129, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-04-07 16:47:12,818] Trial 4 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 166, 'learning_rate': 0.03723744734257787, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-04-07 16:47:16,413] Trial 5 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 193, 'learning_rate': 0.024106766806486636, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-04-07 16:47:18,432] Trial 6 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 104, 'learning_rate': 0.18940294047262024, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-04-07 16:47:22,660] Trial 7 finished with value: 0.7206703910614526 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 138, 'learning_rate': 0.03636918964229144, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-04-07 16:47:22,697] Trial 8 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.252429321935496, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-04-07 16:47:22,731] Trial 9 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 6.873366847927639, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-04-07 16:47:22,760] Trial 10 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10280168326074748, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7877094972067038.
[I 2026-04-07 16:47:22,788] Trial 11 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11304208869622426, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:22,817] Trial 12 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13193455598845424, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:22,933] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 24.881941638996345, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:22,967] Trial 14 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 1.281224569404002, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:22,995] Trial 15 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10550836456546661, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,135] Trial 16 finished with value: 0.7430167597765364 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,499] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.98735093266082, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,538] Trial 18 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 3.7543513267956827, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,815] Trial 19 finished with value: 0.7467411545623835 and parameters: {'classifier': 'RandomForest', 'n_estimators': 50, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,850] Trial 20 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.41414318380888887, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,878] Trial 21 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11143918038172307, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,910] Trial 22 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10756160343286865, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,941] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23461353008278532, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:24,975] Trial 24 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6978284267398626, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:25,003] Trial 25 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21015782383409018, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:25,039] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.6896853375191305, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:25,070] Trial 27 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.19040354668501247, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:27,258] Trial 28 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 287, 'learning_rate': 0.2756167107482787, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:28,341] Trial 29 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 248, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:28,790] Trial 30 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 79, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:28,821] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10995406308835469, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:28,849] Trial 32 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11267043326630459, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:28,880] Trial 33 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4719320886079608, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:28,911] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1708484716597137, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:28,947] Trial 35 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.323144550068403, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:28,988] Trial 36 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.16949332032647463, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:31,842] Trial 37 finished with value: 0.7783985102420856 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 241, 'learning_rate': 0.010321762527709352, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:31,893] Trial 38 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.73326101690772, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:32,932] Trial 39 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 151, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,502] Trial 40 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 255, 'learning_rate': 0.09886097324243963, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,532] Trial 41 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1180669024018628, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,562] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16894821668796217, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,590] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10545987261696364, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,619] Trial 44 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.168040317610574, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,659] Trial 45 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 0.3072679337679581, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,690] Trial 46 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.506724880619788, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,718] Trial 47 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14936018306295448, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:35,761] Trial 48 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 0.28186605448513946, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:38,830] Trial 49 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 199, 'learning_rate': 0.011809528828232566, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:38,897] Trial 50 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 9.233704425676505, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:38,931] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13168237688218948, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:38,960] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.157256851020972, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:38,991] Trial 53 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23622319690270555, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,028] Trial 54 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.10002234730731864, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,057] Trial 55 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14041026380441798, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,086] Trial 56 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24937466902818908, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,122] Trial 57 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 0.34205917804112035, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,700] Trial 58 finished with value: 0.7541899441340781 and parameters: {'classifier': 'RandomForest', 'n_estimators': 106, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,728] Trial 59 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14061062266452948, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,833] Trial 60 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 18.373588676469467, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,863] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1271323381041479, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,892] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13784834521303085, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,924] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2101363018997622, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,954] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13446995257798935, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:39,992] Trial 65 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.10033245811933512, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:40,303] Trial 66 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 79.82718180159151, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:40,338] Trial 67 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.21763769829611107, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:45,969] Trial 68 finished with value: 0.7486033519553074 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 222, 'learning_rate': 0.09823516290231539, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,223] Trial 69 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 51, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,264] Trial 70 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.367444851182661, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,293] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15226476733489733, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,323] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1920962528200845, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,352] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1368391967799916, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,401] Trial 74 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.6790242828757846, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,431] Trial 75 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4059342692749465, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,460] Trial 76 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12330242874393663, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,502] Trial 77 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.18422863374676454, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:46,534] Trial 78 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1001464940440582, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:48,694] Trial 79 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 272, 'learning_rate': 0.09045618198010781, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:48,749] Trial 80 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.5246671126607287, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-04-07 16:47:48,780] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15360814281848367, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.

In [36]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.11304208869622426, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [37]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.772812,2026-04-07 16:47:04.953363,2026-04-07 16:47:07.780637,0 days 00:00:02.827274,NaN,False,RandomForest,NaN,NaN,NaN,18.0,9.0,10.0,214.0,COMPLETE
1,1,0.759777,2026-04-07 16:47:07.782804,2026-04-07 16:47:07.926378,0 days 00:00:00.143574,0.881278,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.782123,2026-04-07 16:47:07.928824,2026-04-07 16:47:07.972885,0 days 00:00:00.044061,0.380912,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.759777,2026-04-07 16:47:07.974021,2026-04-07 16:47:09.153011,0 days 00:00:01.178990,NaN,True,RandomForest,NaN,NaN,NaN,11.0,2.0,3.0,129.0,COMPLETE
4,4,0.750466,2026-04-07 16:47:09.155959,2026-04-07 16:47:12.818218,0 days 00:00:03.662259,NaN,NaN,GradientBoosting,NaN,NaN,0.037237,16.0,6.0,8.0,166.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.772812,2026-04-07 16:47:50.076495,2026-04-07 16:47:50.121108,0 days 00:00:00.044613,0.112584,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.785847,2026-04-07 16:47:50.122173,2026-04-07 16:47:50.156610,0 days 00:00:00.034437,0.257825,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.756052,2026-04-07 16:47:50.157627,2026-04-07 16:47:51.720594,0 days 00:00:01.562967,NaN,NaN,GradientBoosting,NaN,NaN,0.023751,11.0,3.0,7.0,85.0,COMPLETE
98,98,0.789572,2026-04-07 16:47:51.721721,2026-04-07 16:47:51.752581,0 days 00:00:00.030860,0.121889,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.787709,2026-04-07 16:47:51.753603,2026-04-07 16:47:51.783254,0 days 00:00:00.029651,0.184877,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [38]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
GradientBoosting    11
RandomForest        10
Name: count, dtype: int64

In [39]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.749450
RandomForest        0.763128
SVM                 0.777597
Name: value, dtype: float64

In [40]:
# 1. Optimization History
plot_optimization_history(study).show()

In [41]:
# 2. Slice Plot
plot_slice(study).show()

In [42]:
# 3. Hyperparameter Importance
plot_param_importances(study).show()